version: '3.1'

services:
    postgresql:
        hostname: postgresql
        container_name: pg_container
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
            POSTGRES_DB: postgres
        volumes:
            - ./pgdata:/var/lib/postgresql/data/
        ports:
            - "5432:5432"
        networks:
            - backend

    pgadmin:
        depends_on:
            - postgresql
        hostname: pgadmin4
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: test@test.com
            PGADMIN_DEFAULT_PASSWORD: test
        volumes:
            - ./servers.json:/pgadmin4/servers.json
        ports:
            - "80:80"
        networks:
            - backend

networks:
    backend:
